Faster merge tracks
mido/mido pull request #474
Opened 2023-04-05 08:28 UTC by almostimplemented

Small and low priority performance enhancement to `mido.merge_tracks`. Skip redundant data checks. When you have a `MidiFIle` that you want to iterate over, its messages should already have passed `mido.checks`. 

I made `merge_tracks` skip the checks by default, but since it is exposed to clients, maybe it should continue existing behavior by default and only change for internal invocations (like iterating over a `MidiFile`).

2023-04-05 22:44 UTC, rdoursenaud reviewed
Thanks!
The approach is good yet I'm not sure about the implementation details.
I'm not a big fan of skipping checks by default in the `tracks.py` methods.
I must recognize I don't know what would be the consequences of bad data there.
Also, in `messages.py`, shouldn't we check if we get `overrides` regardless of the `skip_checks` status?

2023-04-06 02:08 UTC, almostimplemented commented
> I'm not a big fan of skipping checks by default in the `tracks.py` methods.

I think you are right -- I will change the default to enforce checks and only pass the skip flag internally.

> Also, in `messages.py`, shouldn't we check if we get `overrides` regardless of the `skip_checks` status?

Oof, duh! What an awful mistake. Fixed.

2023-04-06 02:15 UTC, almostimplemented commented
For reference, the `benchmark.py` script in #472 takes 0.913 seconds on `main` and 0.175 seconds on the PR branch.

2023-04-06 05:25 UTC, rdoursenaud requested changes

2023-04-06 05:25 UTC, rdoursenaud commented on mido/midifiles/tracks.py
> +    By default, assumes the messages in tracks have already been
The docstring is now out of sync with the declaration.

2023-05-04 18:06 UTC, rdoursenaud approved these changes

2023-07-04 08:32 UTC, rdoursenaud commented
@almostimplemented Could you please review the test error and fix the merging conflicts. You may want to rebase upon the current main as I have fixed a bunch of GitHub workflow test errors. Thanks!

2023-11-29 11:26 UTC, rdoursenaud commented
@akx Yeah, I'm pondering moving to dedicated objects instead, like what CircuitPython's [adafruit_midi](https://docs.circuitpython.org/projects/midi/en/latest/api.html).

I'm gathering all insights for v2 in https://github.com/orgs/mido/discussions/540

2023-11-29 12:52 UTC, almostimplemented commented
Sorry for the very delayed reply. 

I suppose if you plan to remove the checks altogether, this particular change won't be necessary. But if you want to roll it in, I fixed the broken test and rebased.

2023-11-30 01:26 UTC, rdoursenaud commented
No problem, thank you for your contribution!

I'll merge your work since it's useful for mido 1.x users even if I get rid of it for v.2.

2023-11-30 01:26 UTC, merged